version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - $DB_PORT:5432
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh
    volumes:
      - .:/app
    ports:
      - $APP_PORT:3000
      - $PRISMA_PORT:5555
    environment:
      - NODE_ENV=development
    tty: true
    depends_on:
      - db

volumes:
  db_data:
